// token types
export const GET_TOKEN_API = 'GET_TOKEN_API';
export const RECEIVE_TOKEN_SUCCESS = 'RECEIVE_TOKEN_SUCCESS';
export const RECEIVE_TOKEN_FAILURE = 'RECEIVE_TOKEN_FAILURE';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

// player types
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const SAVE_PLAYER_SCORE = 'SAVE_PLAYER_SCORE';

// quiz types
export const REQUEST_QUIZ_API = 'REQUEST_QUIZ_API';
export const RECEIVE_QUIZ_SUCCESS = 'RECEIVE_QUIZ_SUCCESS';
export const RECEIVE_QUIZ_FAILURE = 'RECEIVE_QUIZ_FAILURE';
